CREATE TABLE `cbm`.`cbmtable1` (
  `item1` CHAR(1) NULL,
  `item2` CHAR(6) NULL,
  `subject` CHAR(7) NULL,
  `course` CHAR(7) NULL,
  `crn` CHAR(7) NOT NULL,
  `item6` CHAR(1) NULL,
  `building` CHAR(6) NULL,
  `room` CHAR(16) NULL,
  `days` CHAR(7) NULL,
  `time` CHAR(4) NULL,
  `duration` CHAR(3) NULL,
  `semester` CHAR(1) NULL,
  `year` CHAR(4) NULL,
  `room_type` CHAR(3) NULL,
  `enrollment` CHAR(15) NULL,
  `enrollment_excess` CHAR(3) NULL,
  `enrollment_de_excess` CHAR(3) NULL,
  `enrollment_ugl_affected` CHAR(3) NULL,
  `enrollment_ugu_affected` CHAR(3) NULL,
  PRIMARY KEY (`crn`));